version: '3.8'

services:
  app:
    image: node:latest
    command: tail -f /dev/null
    container_name: nestjs-proxigo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always

  db:
    image: mysql:latest
    container_name: mysql-proxigo
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-proxigo
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql-proxigo
      PMA_USER: root
      PMA_PASSWORD: root
